[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Johan Olsson <kurnos@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.2.1"
petgraph = "0.4.13"
itertools = "0.8.2"
num = "0.2.0"
bit-set = "0.5.1"
regex = "1.3.1"
pathfinding = "2.0.2"
mod_exp = "1.0.1"
colored = "2"
